spring.application.name=event-ledger
spring.datasource.url=jdbc:postgresql://localhost:5432/ledger
spring.datasource.username=ledger
spring.datasource.password=ledger
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.threads.virtual.enabled=true

spring.jackson.property-naming-strategy=SNAKE_CASE

# Batch related
sweeper.fixed-delay-ms=5000
sweeper.initial-delay-ms=5000
sweeper.batch-size=50

logging.level.root=WARN
# Specific package
logging.level.com.flashsale.ledger=DEBUG

# Framework packages
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE