spring.application.name=event-ledger
spring.datasource.url=jdbc:postgresql://localhost:5432/ledger
spring.datasource.username=ledger
spring.datasource.password=ledger
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.threads.virtual.enabled=true

spring.jackson.property-naming-strategy=SNAKE_CASE